### ISSUE TITLE
能不能支持自定义的属性标识？

### ISSUE THREAD

**Issue by xiaohuoni** [jsx-plus/babel-plugin-transform-jsx-class#3]
现在 `const DIRECTIVE = 'x-class';`
不知道能不能改一下，允许配置这个值？
我是想在 react 中像 solidjs 这样用。
https://www.solidjs.com/docs/latest/api#classlist
```
<div
  classList={{ active: state.active, editing: state.currentId === row.id }}
/>
```

**Comment by wssgcg1213** [comment]
cc @kingback 
已发布, beta 0.1.4, 你先用一段时间, 没有问题的话跟我反馈下我改成 latest
```
dist-tags:
beta: 0.1.4    latest: 0.1.3
```

**Comment by xiaohuoni** [comment]
👍
